name: Build and Package MovieSweep

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Publish Executable
        run: dotnet publish -c Release -o ./publish

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MovieSweep
          path: ./publish/
          compression-level: 0  # Optional: Adjust compression (0-9, 0 for no compression)
          retention-days: 7      # Optional: Store artifacts for 7 days

  release:
    needs: build
    runs-on: windows-latest
    if: github.event_name == 'release'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: MovieSweep
          path: ./publish/

      - name: Zip Release
        run: Compress-Archive -Path ./publish/* -DestinationPath MovieSweep.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: MovieSweep.zip
